#!/bin/bash
# RTL Testing Script for Hebrew Support in iTerm2
# Run this script to verify if RTL is working correctly

echo "=== RTL Testing for Hebrew ==="
echo ""
echo "Test 1: Pure Hebrew (should be RTL)"
echo "שלום עולם"
echo ""
echo "Test 2: Mixed text (may have issues)"
echo "Hello שלום World"
echo ""
echo "Test 3: Numbers + Hebrew"
echo "123 תפוחים"
echo ""
echo "Test 4: Longer sentence"
echo "זה טקסט בעברית שצריך להיות מימין לשמאל"
echo ""
echo "Test 5: English + Hebrew + English"
echo "The word שלום means peace"
echo ""
echo "=== Expected Behavior ==="
echo "✓ Test 1: Should display right-to-left"
echo "⚠ Test 2: May show incorrect ordering (known issue)"
echo "⚠ Test 3: Numbers may separate from text"
echo "✓ Test 4: Full RTL sentence should work"
echo "⚠ Test 5: Mixed ordering issues likely"
echo ""
echo "If tests 1 and 4 display right-to-left, RTL is working!"
echo "For mixed text issues, see RTL_HEBREW_SUPPORT_GUIDE.md"
